# Generated by Django 5.2.6 on 2025-09-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_brief', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
